# Project information
site_name: 云原生虚拟化充电站
site_url: https://ikubevirt.cn/
site_author: Peter Liao
site_description: 本文档主要用于学习和记录云原生虚拟化的相关知识
# Repository
repo_name: ikubevirt/ikubevirt.github.io
repo_url: https://github.com/ikubevirt/ikubevirt.github.io

# Copyright
copyright: Copyright &copy; 2023 - 2023 Peter Liao

theme:
  name: material
  logo: assets/images/kubeVirt-logo-green.png
  favicon: assets/images/kubeVirt-logo-green.png
  language: zh
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  custom_dir: material/.overrides
  features:
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      - content.tabs.link
      - content.tooltips
      # - header.autohide
      - navigation.expand
      - navigation.footer
      - navigation.indexes
      # - navigation.instant
      # - navigation.prune
      # - navigation.sections
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.path
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      # - toc.integrate
  palette:
    - scheme: dracula
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - mike:
      version_selector: false
      canonical_version: null
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - zh
  - minify:
      minify_html: true

extra:
  comments:
    enabled: true
    # defaults to utterances unless replaced with mode: giscus
    mode: utterances
    type: issues
  version:
    provider: mike
    default: latest

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
#      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - neoteroi.spantable
  - neoteroi.timeline
  - neoteroi.cards
  - neoteroi.projects
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''

# Page tree
nav:
  - 首页: index.md
  - KubeVirt:
      - kubeVirt/index.md
      - 快速了解:
          - 架构与生命周期管理: kubeVirt/kubeVirt/quick-learn.md
          - 虚拟机部署实战: kubeVirt/kubeVirt/quick-deploy.md
      - 资源列表:
          - 虚拟机实例:
              - vm资源: kubeVirt/resource/virtualMachine.md
              - vmPool资源: kubeVirt/resource/virtualMachinePool.md
              - vmi资源: kubeVirt/resource/virtualMachineInstance.md
              - vmirs资源: kubeVirt/resource/virtualMachineInstanceReplicaSet.md
              - vmiPreset资源: kubeVirt/resource/virtualMachineInstancePreset.md
              - vmExport资源: kubeVirt/resource/virtualMachineExport.md
          - 虚拟机迁移:
              - vmiMigration资源: kubeVirt/resource/virtualMachineInstanceMigration.md
              - migrationPolicy资源: kubeVirt/resource/migrationPolicy.md
          - 虚拟机快照:
              - vmSnapshot资源: kubeVirt/resource/virtualMachineSnapshot.md
              - vmRestore资源: kubeVirt/resource/virtualMachineRestore.md
      - 特性功能:
          - 节点管理:
            - 节点分配: kubeVirt/features/node-assignment.md
            - 节点维护: kubeVirt/features/node-maintenance.md
            - 节点过度使用管理: kubeVirt/features/node-overcommit.md
          - 内存管理:
            - 内核同页合并: kubeVirt/features/ksm.md
            - 虚拟机内存转储: kubeVirt/features/vm-mem-dump.md
          - 构建管理:
            - Tekton:
              - kubeVirt/features/tekton/index.md
              - Tekton安装: kubeVirt/features/tekton/installation.md
              - Tekton任务: kubeVirt/features/tekton/tekton-task.md
      - Operators:
          - HCO: kubeVirt/operators/hyperConverged-cluster-operator.md
          - SSP: kubeVirt/operators/ssp-operator.md
      - 源码分析:
          - virt-controller:
              - 启动流程: kubeVirt/sourceCodeAnalysis/virt-controller/virt-controller-start.md
              - vmController: kubeVirt/sourceCodeAnalysis/virt-controller/vm-controller.md
              - vmiController: kubeVirt/sourceCodeAnalysis/virt-controller/vmi-controller.md
          - virt-launcher: kubeVirt/sourceCodeAnalysis/virt-launcher.md
          - virt-handler: kubeVirt/sourceCodeAnalysis/virt-handler.md
  - CDI:
      - cdi/index.md
      - 快速了解: cdi/quick-learn.md
      - 资源列表:
          - DV资源: cdi/resource/dataVolume.md
          - DIC资源: cdi/resource/dataImportCron.md
          - 对象传输资源: cdi/resource/objectTransfer.md
      - 特性功能:
          - 热插拔卷: cdi/features/hotplug-volume.md
  - 存储:
      - storage/index.md
      - Local本地存储:
          - HostPath: storage/local/hostPath.md
          - Local PV: storage/local/localPv.md
      - OpenEBS存储:
          - 控制平面: storage/openEBS/control-plane.md
          - 数据平面: storage/openEBS/data-plane.md
          - 节点磁盘管理器: storage/openEBS/node-disk-manager.md
          - 部署安装: storage/openEBS/installation.md
      - Ceph存储:
          - 架构和组件: storage/ceph/infrastructure.md
          - 块存储: storage/ceph/block-storage.md
          - 部署安装: storage/ceph/installation.md
  - GPU:
      - gpu/index.md
  - 网络:
      - network/index.md
  - 监控:
      - monitor/index.md
  - 关于:
      - about.md
