# Project information
site_name: 云原生虚拟化充电站
site_url: https://hyperter96.github.io/cloud-native-docs/
site_author: Peter Liao
site_description: 本文档主要用于学习和记录云原生虚拟化的相关知识
# Repository
repo_name: hyperter96/cloud-native-docs
repo_url: https://github.com/hyperter96/cloud-native-docs

# Copyright
copyright: Copyright &copy; 2021 - 2023 Peter Liao

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: material/.overrides
  features:
      - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      # - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      - navigation.indexes
      # - navigation.instant
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.path
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 首页: index.md
  - KubeVirt:
      - kubeVirt/index.md
      - VirtualMachine: kubeVirt/virtualMachine.md
      - VirtualMachineInstance: kubeVirt/virtualMachineInstance.md
  - CDI:
      - cdi/index.md
  - GPU:
      - gpu/index.md
  - 网络:
      - network/index.md
  - 监控:
      - monitor/index.md
  - 关于:
      - about.md