name: build
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install "mkdocs-material>=9.1.21" \
              "mkdocs-minify-plugin>=0.7.1" \
              "jieba>=0.42.1" \
              "mkdocs-glightbox>=0.3.4" \
              "mkdocs-git-revision-date-localized-plugin>=1.2.0" \
              "neoteroi-mkdocs>=1.0.4" \
              "mike>=1.1.2" \
              "mkdocs-blogging-plugin>=2.2.11"
      - run: python -m mkdocs gh-deploy --force
